import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import home from "../public/home.jpeg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.title}>
          <Image src={home} alt="Home" layout="fill" objectFit="cover" />
        </section>

        <section className={styles.content}>
          <div className={styles.resources}>
            <div className={styles.card}>
              <div className={styles.cardContent}>
                <h2>Calcule</h2>
                <div className={styles.description}>
                  <h3>o Capital de Giro que a sua empresa precisa</h3>
                </div>
                <Link href="/capital-de-giro">
                  <a>Clique aqui</a>
                </Link>
              </div>
            </div>
            <div className={`${styles.card} ${styles.yellow}`}>
              <div className={styles.cardContent}>
                <h2>Descubra</h2>
                <div className={styles.description}>
                  <h3>o valor necessário para o 13 dos funcionários</h3>
                </div>
                <Link href="/capital-de-giro">
                  <a>Clique aqui</a>
                </Link>
              </div>
            </div>
            <div className={`${styles.card} ${styles.blue}`}>
              <div className={styles.cardContent}>
                <h2>Compre</h2>
                <div className={styles.description}>
                  <h3>equipamentos e mão de obra</h3>
                </div>
                <Link href="/capital-de-giro">
                  <a>Clique aqui</a>
                </Link>
              </div>
            </div>
            <div className={`${styles.card} ${styles.white}`}>
              <div className={styles.cardContent}>
                <h2>Invista</h2>
                <div className={styles.description}>
                  <h3>hoje para alcancar o lucro amanhã</h3>
                </div>
                <Link href="/capital-de-giro">
                  <a>Clique aqui</a>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
